#!/bin/bash
echo Installing LunaBuild!
mkdir -p ./lunabuild
onlinerepo="https://raw.githubusercontent.com/LunaWave/lunabuild/resources/"
builds="https://raw.githubusercontent.com/LunaWave/lunabuild/"
newestversion=$(curl "$onlinerepo"version)
cd ./lunabuild
curl "$builds"release-"$newestversion"/build.sh >> ./build.sh
chmod +x ./build.sh
./build.sh &
cd ..
rm "$0"
